const testConstants = {
  TITLE: "Tennis Game",
  SCORE_TITLE: "Score",
  GAME_SCORE: "score",
  PLAYER_ONE: "Player One",
  PLAYER_TWO: "Player Two",
  PLAYER_ONE_TITLE: "Title Player One",
  PLAYER_TWO_TITLE: "Title Player Two",
  SCORED: "Scored",
  ZERO: 0,
  LOVE: 0,
  ONCE: 1,
  TWICE: 2,
  THRICE: 3,
  FOUR_TIMES: 4,
  LOVE_ALL: "Love-All",
  FIFTEEN_LOVE: "Fifteen-Love",
  THIRTY_LOVE: "Thirty-Love",
  FORTY_LOVE: "Forty-Love",
  LOVE_FIFTEEN: "Love-Fifteen",
  LOVE_THIRTY: "Love-Thirty",
  LOVE_FORTY: "Love-Forty",
  FIFTEEN_ALL: "Fifteen-All",
  THIRTY_ALL: "Thirty-All",
  FIFTEEN_THIRTY: "Fifteen-Thirty",
  DEUCE: "Deuce",
  PLAYER_ONE_WIN: "Player One Win",
  PLAYER_TWO_WIN: "Player Two Win",
  PLAYER_ONE_ADVANTAGE: "Player One Advantage"
};

export { testConstants };
